server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    bus:
      enabled: true
      id: cloud-config-server
      destination: cloud-config-topic
      trace:
        enabled: true
      refresh:
        enabled: true
    config:
      server:
        git:
          uri: https://gitlab.com/path/to/my/configuration-repo.git
          search-paths: '{application}'
          clone-on-start: true
          username: oauth2
          password: glpat--LQaRkjTetYeThFmbRTJ

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
  health:
    binders:
      enabled: true
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      env: ${ENV:env-not-set}
      team: ${TEAM:team-name-not-set}
      service: ${spring.application.name:applicaton-name-not-set}
  statsd:
    metrics:
      export:
        enabled: true
        port: 8125
        flavor: datadog
        host: ${DD_AGENT_HOST}